spring.application.name=bookshop
// spring.data.mongodb.uri=mongodb+srv://RamOfFate:stormyocus@bookshop.bbr08nr.mongodb.net/bookshop?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://RamOfFate:stormyocus@bookshop.bbr08nr.mongodb.net/bookshop?retryWrites=true&w=majority
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG