spring.application.name=bookshop-service
server.port=8080

spring.data.mongodb.uri=mongodb+srv://RamOfFate:stormyocus@bookshop.bbr08nr.mongodb.net/bookshop?retryWrites=true&w=majority
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
