spring.application.name=bookshop

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:./data/bookshop
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ram
spring.datasource.password=storm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true